import {NextResponse} from 'next/server';
import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
import {requireProUser} from '../../../../lib/server/access.js';
import {createSupabaseAdmin} from '../../../../lib/server/supabase-admin.js';
import {sendTransactionalEmail} from '../../../../lib/server/email.js';

async function imageBytes(src=''){if(src.startsWith('data:')){const [,meta,b64]=src.match(/^data:([^;]+);base64,(.+)$/)||[];return meta&&b64?{type:meta,bytes:Buffer.from(b64,'base64')}:null}try{const r=await fetch(src);if(!r.ok)return null;return{type:r.headers.get('content-type')||'image/jpeg',bytes:Buffer.from(await r.arrayBuffer())}}catch{return null}}
async function buildPdf({projectName,items}){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),W=595.28,H=841.89;const cover=pdf.addPage([W,H]);cover.drawText('SET',{x:44,y:790,size:16,font:bold});cover.drawText('CASTING SELECTION',{x:44,y:680,size:11,font:bold,color:rgb(.8,0,0)});cover.drawText(String(projectName||'Casting').slice(0,55),{x:44,y:630,size:30,font:bold,maxWidth:500});cover.drawText(`${items.length} selected model${items.length===1?'':'s'}`,{x:44,y:590,size:11,font,color:rgb(.4,.4,.4)});
 for(let i=0;i<items.length;i++){const m=items[i],page=pdf.addPage([W,H]);page.drawText(`CHOICE ${m.choice||'—'}`,{x:42,y:800,size:9,font:bold,color:rgb(.8,0,0)});page.drawText(String(m.talentName||m.name||'Model').slice(0,50),{x:42,y:765,size:25,font:bold});page.drawText(String(m.agency||'Independent').slice(0,70),{x:42,y:742,size:10,font,color:rgb(.4,.4,.4)});const ib=await imageBytes(m.src);if(ib){try{const img=ib.type.includes('png')?await pdf.embedPng(ib.bytes):await pdf.embedJpg(ib.bytes),scale=Math.min(300/img.width,500/img.height);page.drawImage(img,{x:42,y:210,width:img.width*scale,height:img.height*scale})}catch{}}
 const details=[['STATUS',m.status],['CITY',m.city],['HEIGHT',m.height],['BUST / CHEST',m.bust],['WAIST',m.waist],['HIPS',m.hips],['SHOES',m.shoes],['AVAILABILITY',m.availability],['EMAIL',m.email],['PHONE',m.phone]].filter(x=>x[1]);let y=690;for(const [k,v] of details){page.drawText(k,{x:375,y,size:7,font:bold,color:rgb(.45,.45,.45)});page.drawText(String(v).slice(0,28),{x:375,y:y-15,size:10,font});y-=48}if(m.notes){page.drawText('NOTES',{x:375,y:Math.max(120,y),size:7,font:bold,color:rgb(.45,.45,.45)});page.drawText(String(m.notes).slice(0,220),{x:375,y:Math.max(100,y-16),size:8,font,maxWidth:175,lineHeight:11})}}return Buffer.from(await pdf.save())}
export async function POST(req){try{const user=await requireProUser();const body=await req.json(),email=String(body.email||'').trim(),items=Array.isArray(body.items)?body.items:[],projectId=body.projectId;if(!email||!items.length||!projectId)return NextResponse.json({error:'Email, project and selected models are required'},{status:400});const db=createSupabaseAdmin();const {data:project}=await db.from('projects').select('id,name,owner_id').eq('id',projectId).maybeSingle();if(!project||project.owner_id!==user.id)return NextResponse.json({error:'Project not found or access denied'},{status:403});const pdf=await buildPdf({projectName:body.projectName||project.name,items});await sendTransactionalEmail({to:email,replyTo:user.email,subject:`SET · Casting PDF · ${body.projectName||project.name}`,html:`<div style="font-family:Helvetica Neue,Helvetica,Arial,sans-serif"><p>SET</p><h1>Casting selection</h1><p>Please find the selected models attached as a PDF.</p></div>`,attachments:[{filename:`${String(project.name||'casting').replace(/[^a-z0-9]+/gi,'-')}-casting.pdf`,content:pdf}]});return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e?.message||'Could not send casting PDF'},{status:e?.message==='UNAUTHORIZED'?401:e?.message==='SUBSCRIPTION_REQUIRED'?402:500})}}
