import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

const money = (v, c='EUR') => new Intl.NumberFormat('en-IE',{style:'currency',currency:c}).format(Number(v||0));
const safe = (v='') => String(v).replace(/[\r\n]+/g,' ').slice(0,180);

export async function buildInvoicePdf({invoice, items=[], owner={}, client={}}) {
  const pdf = await PDFDocument.create();
  let page = pdf.addPage([595.28, 841.89]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const black = rgb(0.05,0.05,0.05), red = rgb(0.86,0.04,0.08), grey = rgb(0.42,0.42,0.42);
  let y=790;
  const text=(t,x,size=10,opts={})=>page.drawText(safe(t),{x,y:opts.y??y,size,font:opts.bold?bold:font,color:opts.color||black,maxWidth:opts.maxWidth});
  text('SET',48,26,{bold:true,color:red});
  text(invoice.type==='deposit'?'DEPOSIT INVOICE':'INVOICE',390,18,{bold:true}); y-=42;
  text(`Invoice ${invoice.invoice_number||''}`,390,10,{color:grey}); y-=14;
  text(`Issue: ${invoice.issue_date||''}`,390,9,{color:grey}); y-=14;
  text(`Due: ${invoice.due_date||''}`,390,9,{color:grey});
  y=700; text(owner.display_name||owner.business_name||'SET user',48,11,{bold:true}); y-=16;
  for (const line of [owner.address, owner.siret && `SIRET ${owner.siret}`, owner.email].filter(Boolean)){text(line,48,9,{color:grey});y-=13}
  y=700; text('BILL TO',330,9,{bold:true,color:red}); y-=17; text(client.name||invoice.client_name||'Client',330,11,{bold:true}); y-=15;
  for (const line of [client.address,client.email].filter(Boolean)){text(line,330,9,{color:grey});y-=13}
  y=600; page.drawLine({start:{x:48,y},end:{x:548,y},thickness:1,color:black}); y-=24;
  text('DESCRIPTION',48,9,{bold:true}); text('QTY',360,9,{bold:true,y}); text('UNIT',410,9,{bold:true,y}); text('TOTAL',490,9,{bold:true,y}); y-=20;
  for (const item of items){
    if(y<170){page=pdf.addPage([595.28,841.89]);y=780}
    text(item.description||'Service',48,9,{maxWidth:285}); text(String(item.quantity??1),365,9,{y}); text(money(item.unit_price,invoice.currency),410,9,{y}); text(money((item.quantity||1)*(item.unit_price||0),invoice.currency),485,9,{y}); y-=22;
  }
  y-=10; page.drawLine({start:{x:330,y},end:{x:548,y},thickness:1,color:black}); y-=24;
  text('Subtotal',360,10); text(money(invoice.subtotal,invoice.currency),475,10,{y}); y-=18;
  text('VAT',360,10); text(money(invoice.vat,invoice.currency),475,10,{y}); y-=20;
  text('TOTAL',360,12,{bold:true}); text(money(invoice.total,invoice.currency),465,12,{bold:true,y,color:red});
  y=100; if(invoice.notes){text(invoice.notes,48,8,{color:grey,maxWidth:500});y-=15}
  text('Generated by SET · Review legal and tax details before sending.',48,7,{color:grey});
  return Buffer.from(await pdf.save());
}
