'use client';
import {useEffect,useMemo,useState} from 'react';
import './style.css';
import {calculateTaxReserve, calculateLatePayment, collectionStage} from '../lib/finance-rules.js';
import {yearlySavingPercent} from '../lib/billing.js';

const seedProjects=[
{id:'nike',name:'NIKE RUNNING CAMPAIGN',client:'Nike',location:'Paris, France',date:'14 September 2026',status:'Pre-production',progress:72,team:12,budget:12000,spent:7450},
{id:'human',name:'THE HUMAN FORM',client:'VAK PROJECT STUDIO',location:'Paris / Normandy',date:'In development',status:'Casting',progress:68,team:6,budget:10000,spent:4100},
{id:'editorial',name:'EDITORIAL PROJECT',client:'Independent',location:'Paris',date:'Client approval',status:'Waiting',progress:35,team:4,budget:6500,spent:1200}
];
const seedTasks=[
{id:1,title:'Confirm location',project:'nike',due:'Today',done:false,assignee:'Nicholas'},
{id:2,title:'Prepare shot list',project:'nike',due:'Tomorrow',done:false,assignee:'Nicholas'},
{id:3,title:'Book equipment',project:'nike',due:'11 Sep',done:false,assignee:'Production'},
{id:4,title:'Review casting shortlist',project:'human',due:'12 Sep',done:false,assignee:'Nicholas'}
];
const seedEvents=[
{id:1,title:'Creative Meeting',time:'10:00',place:'Studio',project:'nike'},
{id:2,title:'Location Scout',time:'14:00',place:'Paris',project:'nike'},
{id:3,title:'Call with Client',time:'11:00',place:'Online',project:'editorial'}
];
const roles=['Photographer','Creative Director','Producer','Art Director','Stylist','Makeup Artist','Hair Stylist','Videographer','Retoucher','Model'];
function uid(){return Math.random().toString(36).slice(2,9)}
function load(key, fallback){try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}}
function save(key,v){localStorage.setItem(key,JSON.stringify(v))}

export default function Page(){
 const [ready,setReady]=useState(false); const [view,setView]=useState('Dashboard'); const [projects,setProjects]=useState(seedProjects); const [tasks,setTasks]=useState(seedTasks); const [events,setEvents]=useState(seedEvents); const [active,setActive]=useState('nike'); const [modal,setModal]=useState(null); const [search,setSearch]=useState(''); const [toast,setToast]=useState('');
 useEffect(()=>{setProjects(load('set-projects',seedProjects));setTasks(load('set-tasks',seedTasks));setEvents(load('set-events',seedEvents));setReady(true)},[]);
 useEffect(()=>{if(ready)save('set-projects',projects)},[projects,ready]); useEffect(()=>{if(ready)save('set-tasks',tasks)},[tasks,ready]); useEffect(()=>{if(ready)save('set-events',events)},[events,ready]);
 const project=projects.find(p=>p.id===active)||projects[0];
 const notify=(m)=>{setToast(m);setTimeout(()=>setToast(''),2400)};
 const addProject=(data)=>{const p={id:uid(),name:data.name.toUpperCase(),client:data.client||'Independent',location:data.location||'Location not set',date:data.date||'Date not set',status:'Pre-production',progress:0,team:1,budget:Number(data.budget)||0,spent:0};setProjects([p,...projects]);setActive(p.id);setView('Project');setModal(null);notify('Project created');};
 const addTask=(title)=>{if(!title.trim())return;setTasks([...tasks,{id:uid(),title,project:active,due:'No deadline',done:false,assignee:'Nicholas'}]);setModal(null);notify('Task added')};
 const addExpense=(title,amount)=>{setProjects(projects.map(p=>p.id===active?{...p,spent:p.spent+Number(amount||0)}:p));notify(`${title||'Expense'} added`);setModal(null)};
 const filtered=projects.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())||p.client.toLowerCase().includes(search.toLowerCase()));
 if(!ready)return <div className="loading">SET</div>;
 return <main>
  <aside><div className="brand">SET</div><nav>{['Dashboard','Projects','Project','Calendar','Tasks','Finance','Contacts','Network','Messages','Admin'].map(x=><button key={x} className={view===x?'active':''} onClick={()=>setView(x)}>{x==='Project'?'Workspace':x}</button>)}</nav><div className="profile"><b>Nicholas</b><small>Photographer · Owner</small><span>v0.9.2</span></div></aside>
  <section className="content"><header><div><small>{view==='Dashboard'?'Good morning,':'SET / '+view}</small><h1>{view==='Dashboard'?'Nicholas':view==='Project'?project?.name:view}</h1></div><div className="actions"><input className="search" placeholder="Search" value={search} onChange={e=>setSearch(e.target.value)}/><button className="primary" onClick={()=>setModal('project')}>＋ New Project</button></div></header>
  {view==='Dashboard'&&<Dashboard projects={projects} tasks={tasks} events={events} setView={setView} setActive={setActive} notify={notify}/>} 
  {view==='Projects'&&<Projects projects={filtered} setActive={setActive} setView={setView}/>} 
  {view==='Project'&&<Workspace project={project} tasks={tasks.filter(t=>t.project===active)} events={events.filter(e=>e.project===active)} setView={setView} setModal={setModal} notify={notify} setActive={setActive} setProjects={setProjects} setTasks={setTasks}/>} 
  {view==='Calendar'&&<Calendar events={events} projectMap={Object.fromEntries(projects.map(p=>[p.id,p.name]))} setModal={setModal}/>} 
  {view==='Tasks'&&<Tasks tasks={tasks} projects={projects} setTasks={setTasks} setModal={setModal}/>} 
  {view==='Finance'&&<Finance notify={notify}/>} {view==='Admin'&&<Admin notify={notify}/>} {view==='Contacts'&&<Contacts/>} {view==='Network'&&<Network notify={notify}/>} {view==='Messages'&&<Messages notify={notify}/>} 
  </section>
  {modal==='project'&&<ProjectModal onClose={()=>setModal(null)} onCreate={addProject}/>} {modal==='task'&&<SimpleModal title="New task" placeholder="Task name" action="Add task" onClose={()=>setModal(null)} onSubmit={addTask}/>} {modal==='expense'&&<ExpenseModal onClose={()=>setModal(null)} onSubmit={addExpense}/>} {modal==='event'&&<SimpleModal title="New event" placeholder="Event title" action="Add event" onClose={()=>setModal(null)} onSubmit={(title)=>{setEvents([...events,{id:uid(),title,time:'10:00',place:'TBC',project:active}]);setModal(null);notify('Event added')}}/>}
  {toast&&<div className="toast">✓ {toast}</div>}
 </main>
}
function Dashboard({projects,tasks,events,setView,setActive}){return <div className="dashboard"><div className="two-col"><div><div className="section-title">Active Projects <span>{projects.length}</span></div>{projects.map((p,i)=><button className={'project-card c'+i} key={p.id} onClick={()=>{setActive(p.id);setView('Project')}}><div><b>{p.name}</b><small>{p.location} · {p.date}</small><em>{p.status}</em></div><div className="percent">{p.progress}%</div><div className="progress"><i style={{width:p.progress+'%'}}/></div><footer>{p.team} team members <span>Next event →</span></footer></button>)}</div><div className="right"><Panel title="Upcoming" action="View calendar"><div className="timeline">{events.map(e=><div key={e.id}><b>{e.time}</b><span>{e.title}<small>{e.place}</small></span></div>)}</div></Panel><Panel title="Tasks" action="View all"><div className="task-list">{tasks.filter(t=>!t.done).slice(0,5).map(t=><div key={t.id}>□ <span>{t.title}</span><small>{t.due}</small></div>)}</div></Panel></div></div></div>}
function Projects({projects,setActive,setView}){return <><div className="section-title">All projects <span>{projects.length}</span></div><div className="project-grid">{projects.map((p,i)=><button className={'project-card grid-card c'+(i%3)} key={p.id} onClick={()=>{setActive(p.id);setView('Project')}}><div><b>{p.name}</b><small>{p.client}</small><em>{p.status}</em></div><div className="percent">{p.progress}%</div><div className="progress"><i style={{width:p.progress+'%'}}/></div><footer>{p.location}<span>{p.date}</span></footer></button>)}</div></>}
function Workspace({project,tasks,events,setView,setModal,notify,setActive,setProjects,setTasks}){const [tab,setTab]=useState('Overview');const [note,setNote]=useState('');const [comments,setComments]=useState([]);const [members,setMembers]=useState([{name:'Nicholas Efimtsev',role:'Photographer',status:'Owner'},{name:'Anna Becker',role:'Art Director',status:'Confirmed'},{name:'Maxime Leroy',role:'Stylist',status:'Confirmed'},{name:'Sarah Dupont',role:'Makeup Artist',status:'Invited'}]); const tabs=['Overview','Moodboard','Team','Chat','Schedule','Tasks','Casting','Budget','Files'];
 return <div><div className="workspace-top"><div><small>{project.client}</small><h2>{project.name}</h2><span>{project.location} · {project.date}</span></div><button className="ghost" onClick={()=>notify('Project link copied')}>Share</button></div><div className="tabs">{tabs.map(t=><button className={tab===t?'tab-active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Overview'&&<div className="overview"><div className="stats"><Stat label="STATUS" value={project.status}/><Stat label="PROGRESS" value={project.progress+'%'}/><Stat label="TEAM" value={project.team+' members'}/><Stat label="BUDGET" value={`€${project.spent.toLocaleString()} / €${project.budget.toLocaleString()}`}/></div><div className="two-col"><Panel title="Next events"><div className="timeline">{events.map(e=><div key={e.id}><b>{e.time}</b><span>{e.title}<small>{e.place}</small></span></div>)}</div></Panel><Panel title="Open tasks"><div className="task-list">{tasks.map(t=><div key={t.id}>□ <span>{t.title}</span><small>{t.due}</small></div>)}</div></Panel></div></div>}
 {tab==='Moodboard'&&<div className="mood"><div className="board-tabs"><b>Visual Direction</b><span>Lighting</span><span>Styling</span><span>Location</span><button onClick={()=>notify('Upload will connect to cloud storage in production')}>＋ Add</button></div><div className="masonry">{['01','02','03','04','05','06'].map((x,i)=><div className={'mood-img m'+i} key={x}><span>{i===0?'APPROVED':''}</span></div>)}</div><div className="comment-box"><input placeholder="Add a moodboard comment…" value={note} onChange={e=>setNote(e.target.value)}/><button onClick={()=>{if(note){setComments([...comments,note]);setNote('');notify('Comment added')}}}>Send</button></div>{comments.map((c,i)=><p className="comment" key={i}>Nicholas · {c}</p>)}</div>}
 {tab==='Team'&&<Panel title={`${members.length} team members`} action="＋ Invite"><div className="people">{members.map((m,i)=><div key={m.name}><i>{m.name.slice(0,1)}</i><span><b>{m.name}</b><small>{m.role}</small></span><em>{m.status}</em></div>)}</div></Panel>}
 {tab==='Chat'&&<Chat notify={notify}/>} {tab==='Schedule'&&<><div className="schedule-head"><button className="primary" onClick={()=>setModal('event')}>＋ Event</button><b>12 September 2026</b></div><div className="schedule">{events.concat([{id:'x1',time:'10:30',title:'Makeup & Hair',place:'Studio A'},{id:'x2',time:'11:30',title:'Look 01',place:'Studio A'},{id:'x3',time:'13:00',title:'Lunch',place:'Catering'},{id:'x4',time:'18:00',title:'Wrap',place:'Studio A'}]).sort((a,b)=>a.time.localeCompare(b.time)).map(e=><div key={e.id}><b>{e.time}</b><span>{e.title}</span><small>{e.place}</small></div>)}</div></>}
 {tab==='Tasks'&&<><button className="primary inline" onClick={()=>setModal('task')}>＋ New Task</button><div className="task-board">{['To Do','In Progress','Completed'].map((col,ci)=><div key={col}><h3>{col}</h3>{tasks.filter((t,i)=>ci===0?!t.done:i%3===ci-1).map(t=><article key={t.id}><button onClick={()=>setTasks(ts=>ts.map(x=>x.id===t.id?{...x,done:!x.done}:x))}>{t.done?'✓':'○'}</button><b>{t.title}</b><small>{t.assignee} · {t.due}</small></article>)}</div>)}</div></>}
 {tab==='Casting'&&<Casting/>} {tab==='Budget'&&<Budget project={project} setModal={setModal}/>} {tab==='Files'&&<Files notify={notify}/>} 
 </div>}
function Panel({title,action,children}){return <div className="panel"><div className="panel-head"><h3>{title}</h3>{action&&<button>{action}</button>}</div>{children}</div>}
function Stat({label,value}){return <div className="stat"><small>{label}</small><b>{value}</b></div>}
function Calendar({events,projectMap,setModal}){return <><button className="primary inline" onClick={()=>setModal('event')}>＋ New Event</button><div className="calendar-grid">{['MON 8','TUE 9','WED 10','THU 11','FRI 12','SAT 13','SUN 14'].map((d,i)=><div key={d}><b>{d}</b>{events.filter((_,x)=>x%7===i%7).map(e=><article key={e.id}>{e.time}<span>{e.title}</span><small>{projectMap[e.project]}</small></article>)}</div>)}</div></>}
function Tasks({tasks,projects,setTasks,setModal}){return <><button className="primary inline" onClick={()=>setModal('task')}>＋ New Task</button><Panel title="All tasks"><div className="all-tasks">{tasks.map(t=><div key={t.id}><button onClick={()=>setTasks(ts=>ts.map(x=>x.id===t.id?{...x,done:!x.done}:x))}>{t.done?'✓':'○'}</button><span><b>{t.title}</b><small>{projects.find(p=>p.id===t.project)?.name||'Project'}</small></span><em>{t.due}</em></div>)}</div></Panel></>}

function Finance({notify}){
 const demoInvoices=[{id:'demo-1',invoice_number:'SET-2026-0001',client_name:'Maison Atelier',invoice_type:'deposit',total:1500,balance_due:1500,due_date:'2026-09-05',status:'sent',client_type:'business'},{id:'demo-2',invoice_number:'SET-2026-0002',client_name:'Studio Client',invoice_type:'final',total:2400,balance_due:2400,due_date:'2026-08-24',status:'overdue',client_type:'business'}];
 const [data,setData]=useState({invoices:demoInvoices,quotes:[],metrics:{paid:0,outstanding:3900,overdue:2400}}),[tab,setTab]=useState('Invoices'),[busy,setBusy]=useState(false),[composer,setComposer]=useState(null);
 const [billing,setBilling]=useState({loading:true,hasCustomer:false,status:null});
 const [turnover,setTurnover]=useState(3400),[rate,setRate]=useState(21.2),[cfp,setCfp]=useState(.3),[tax,setTax]=useState(0);
 const taxCalc=calculateTaxReserve({turnover,socialRate:rate,cfpRate:cfp,incomeTaxReserveRate:tax});
 const refresh=async()=>{try{const r=await fetch('/api/finance/summary',{cache:'no-store'});if(r.ok){const j=await r.json();setData(j);if(j.taxProfile){setRate(Number(j.taxProfile.social_rate??21.2));setCfp(Number(j.taxProfile.cfp_rate??.3));setTax(Number(j.taxProfile.income_tax_reserve_rate??0))}}}catch{}};
 const refreshBilling=async()=>{try{const r=await fetch('/api/billing/status',{cache:'no-store'});if(r.ok){const j=await r.json();setBilling({loading:false,...j})}else setBilling({loading:false,hasCustomer:false,status:null})}catch{setBilling({loading:false,hasCustomer:false,status:null})}};
 useEffect(()=>{refresh();refreshBilling()},[]);
 const createDoc=async(kind,form)=>{setBusy(true);try{const url=kind==='quote'?'/api/quotes':'/api/invoices';const payload={client_name:form.client,client_email:form.email,client_type:'business',deposit_percent:Number(form.deposit||50),items:[{description:form.description||'Photography services',quantity:1,unit_price:Number(form.amount||0),vat_rate:Number(form.vat||0)}]};const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error((await r.json()).error||'Could not create document');setComposer(null);notify(kind==='quote'?'Devis created':'Invoice created');await refresh()}catch(e){notify(e.message)}finally{setBusy(false)}};
 const convert=async(id)=>{setBusy(true);try{const r=await fetch(`/api/quotes/${id}/convert`,{method:'POST'});if(!r.ok)throw new Error((await r.json()).error||'Conversion failed');notify('Deposit invoice created from devis');await refresh()}catch(e){notify(e.message)}finally{setBusy(false)}};
 const sendInvoice=async(id)=>{setBusy(true);try{const r=await fetch(`/api/invoices/${id}/send`,{method:'POST'});if(!r.ok)throw new Error((await r.json()).error||'Send failed');notify('Invoice PDF sent and reminders queued');await refresh()}catch(e){notify(e.message)}finally{setBusy(false)}};
 const checkout=async(planCode)=>{setBusy(true);try{const r=await fetch('/api/billing/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({planCode})}),j=await r.json();if(j.url)location.href=j.url;else notify(j.error||'Checkout unavailable')}catch{notify('Checkout unavailable')}finally{setBusy(false)}};
 const portal=async()=>{try{const r=await fetch('/api/billing/portal',{method:'POST'}),j=await r.json();if(j.url)location.href=j.url;else notify(j.error||'Billing portal unavailable')}catch{notify('Billing portal unavailable')}};
 const invoices=data.invoices||[],quotes=data.quotes||[],m=data.metrics||{};
 return <div><div className="finance-hero"><div><small>FINANCE</small><h2>Quote → Deposit → Invoice → Payment</h2><p>One commercial workflow for production, client approval, deposits, collection reminders and French tax reserves.</p></div><div className="finance-actions">{billing.loading?<button className="ghost" disabled>Checking plan…</button>:billing.hasCustomer?<button className="ghost" onClick={portal}>Manage SET plan</button>:<><button className="ghost" disabled={busy} onClick={()=>checkout('pro_monthly')}>Start monthly · €9.99</button><button className="ghost" disabled={busy} onClick={()=>checkout('pro_yearly')}>Start yearly · €99.99</button></>}<button className="ghost" onClick={()=>setComposer('quote')}>＋ Devis</button><button className="primary" onClick={()=>setComposer('invoice')}>＋ Invoice</button></div></div>{!billing.loading&&!billing.hasCustomer&&<div className="billing-trial-note"><b>SET Pro · 7-day free trial</b><span>Choose monthly or yearly billing. You can manage or cancel the subscription from SET after checkout.</span></div>}
 <div className="stats finance-stats"><Stat label="PAID" value={`€${Number(m.paid||0).toLocaleString()}`}/><Stat label="OUTSTANDING" value={`€${Number(m.outstanding||0).toLocaleString()}`}/><Stat label="OVERDUE" value={`€${Number(m.overdue||0).toLocaleString()}`}/><Stat label="TAX RESERVE" value={`€${taxCalc.reserve.toFixed(2)}`}/></div>
 <div className="tabs finance-tabs">{['Invoices','Quotes','Taxes','Collections'].map(x=><button key={x} className={tab===x?'tab-active':''} onClick={()=>setTab(x)}>{x}</button>)}</div>
 {tab==='Invoices'&&<Panel title="Invoices"><div className="invoice-table"><div className="invoice-row head"><b>Invoice</b><b>Client</b><b>Type</b><b>Due</b><b>Total</b><b>Status</b><b>Action</b></div>{invoices.map(x=>{const late=calculateLatePayment({principal:Number(x.balance_due??x.total),dueDate:x.due_date,annualRate:Number(x.late_penalty_rate||12.15),recoveryFee:Number(x.recovery_fee??40),businessToBusiness:x.client_type==='business'});return <div className="invoice-row" key={x.id}><span>{x.invoice_number}</span><span>{x.client_name||'Client'}</span><span>{x.invoice_type}</span><span>{x.due_date||'—'}</span><b>€{Number(x.total||0).toLocaleString()}</b><em className={late.overdueDays?'danger':''}>{x.status}{late.overdueDays?` · ${late.overdueDays}d`:''}</em><div className="row-actions"><a href={`/api/invoices/${x.id}/pdf`} target="_blank">PDF</a><button disabled={busy} onClick={()=>sendInvoice(x.id)}>Send</button></div></div>})}</div></Panel>}
 {tab==='Quotes'&&<Panel title="Devis / Quotes"><div className="quote-list">{quotes.length===0&&<div className="empty-state">No devis yet. Create one, then convert it into a deposit invoice when the client accepts.</div>}{quotes.map(q=><article key={q.id}><div><b>{q.quote_number}</b><small>{q.client_name||'Client'} · valid until {q.valid_until||'—'}</small></div><strong>€{Number(q.total||0).toLocaleString()}</strong><em>{q.status}</em><button disabled={busy||q.status==='converted'} onClick={()=>convert(q.id)}>{q.status==='converted'?'Converted':`Create ${Number(q.deposit_percent||50)}% deposit`}</button></article>)}</div></Panel>}
 {tab==='Taxes'&&<div className="two-col"><Panel title="French micro-business estimator"><div className="tax-form"><label>Turnover (€)<input type="number" value={turnover} onChange={e=>setTurnover(Number(e.target.value))}/></label><label>Social contributions %<input type="number" step="0.1" value={rate} onChange={e=>setRate(Number(e.target.value))}/></label><label>CFP %<input type="number" step="0.1" value={cfp} onChange={e=>setCfp(Number(e.target.value))}/></label><label>Optional income-tax reserve %<input type="number" step="0.1" value={tax} onChange={e=>setTax(Number(e.target.value))}/></label></div><div className="tax-result"><span>Reserve now</span><b>€{taxCalc.reserve.toFixed(2)}</b><small>Estimation only. Rates are versioned/configurable so rules can be updated without rewriting issued invoices.</small></div></Panel><Panel title="Cash after reserve"><div className="tax-result"><span>Estimated available</span><b>€{Math.max(turnover-taxCalc.reserve,0).toFixed(2)}</b><small>Turnover minus configured social/CFP/tax reserves.</small></div></Panel></div>}
 {tab==='Collections'&&<><Panel title="Collection inbox"><div className="collection-inbox">{(data.collections||[]).length===0&&<div className="empty-state">Collection actions appear here after an invoice is sent.</div>}{(data.collections||[]).map(a=><article key={a.id}><div><b>{a.action_type.replaceAll('_',' ')}</b><small>{a.invoices?.client_name||'Client'} · {a.invoices?.invoice_number||a.invoices?.number||''} · {a.scheduled_for?.slice(0,10)||'—'}</small></div><em>{a.status}</em>{a.requires_approval&&a.status==='pending'?<button onClick={async()=>{const r=await fetch(`/api/collections/${a.id}/approve`,{method:'POST'});notify(r.ok?'Formal notice approved':'Approval failed');refresh()}}>Approve</button>:a.requires_approval&&a.status==='approved'?<button className="danger-button" onClick={async()=>{const r=await fetch(`/api/collections/${a.id}/send`,{method:'POST'});notify(r.ok?'Formal notice sent':'Send failed');refresh()}}>Send formal notice</button>:<span/>}</article>)}</div></Panel><Panel title="Automation rules"><div className="collection-flow"><b>D−7</b><span>Friendly upcoming-due reminder</span><b>Due</b><span>Payment reminder</span><b>D+1 / D+7</b><span>Overdue reminders</span><b>D+14</b><span>Mise en demeure draft — approval required</span><em>SET never auto-approves formal/legal communication. Every action is recorded in the audit log.</em></div></Panel></>}
 {composer&&<FinanceComposer kind={composer} busy={busy} onClose={()=>setComposer(null)} onCreate={f=>createDoc(composer,f)}/>}</div>
}
function FinanceComposer({kind,busy,onClose,onCreate}){const [f,setF]=useState({client:'',email:'',description:'Photography services',amount:'',vat:'0',deposit:'50'});const field=(k,p,t='text')=><label>{p}<input type={t} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>;return <div className="modal"><div className="doc-modal"><div className="modal-head"><h2>{kind==='quote'?'New devis':'New invoice'}</h2><button onClick={onClose}>×</button></div><div className="doc-form">{field('client','Client')}{field('email','Billing email','email')}{field('description','Service')}{field('amount','Amount HT (€)','number')}{field('vat','VAT %','number')}{kind==='quote'&&field('deposit','Deposit %','number')}</div><div className="doc-total">Total <b>€{(Number(f.amount||0)*(1+Number(f.vat||0)/100)).toFixed(2)}</b></div><button className="primary full" disabled={busy||!f.client||!Number(f.amount)} onClick={()=>onCreate(f)}>{busy?'Saving…':kind==='quote'?'Create devis':'Create invoice'}</button></div></div>}
function Admin({notify}){const [monthly,setMonthly]=useState(()=>load('set-monthly',9.99));const [yearly,setYearly]=useState(()=>load('set-yearly',99.99));const [trial,setTrial]=useState(()=>load('set-trial',7));const savePricing=()=>{save('set-monthly',monthly);save('set-yearly',yearly);save('set-trial',trial);notify('Pricing configuration saved')};return <div><div className="finance-hero"><div><small>ADMIN</small><h2>Pricing & platform rules</h2><p>Central configuration for SET. Store billing products will map to these plans.</p></div><button className="primary" onClick={savePricing}>Save changes</button></div><div className="pricing-grid"><article><span>MONTHLY</span><div className="price-input">€<input type="number" step="0.01" value={monthly} onChange={e=>setMonthly(Number(e.target.value))}/><small>/ month</small></div><b>{trial} days free</b></article><article className="recommended"><i>BEST VALUE</i><span>YEARLY</span><div className="price-input">€<input type="number" step="0.01" value={yearly} onChange={e=>setYearly(Number(e.target.value))}/><small>/ year</small></div><b>Save {yearlySavingPercent(monthly*100,yearly*100)}%</b></article><article><span>FREE TRIAL</span><div className="price-input"><input type="number" value={trial} onChange={e=>setTrial(Number(e.target.value))}/><small> days</small></div><b>Editable without redesigning SET</b></article></div><Panel title="Billing architecture"><div className="settings-list"><div><b>iOS</b><span>Apple In-App Purchase / StoreKit mapping</span></div><div><b>Web</b><span>Stripe subscription mapping</span></div><div><b>Entitlements</b><span>One SET access layer across platforms</span></div><div><b>Existing subscribers</b><span>Support grandfathered prices when plans change</span></div></div></Panel></div>}

function Contacts(){const contacts=['Nike Creative Team','IMG Models','Anna Becker','Maxime Leroy','Studio A','Production House'];return <Panel title="Contacts"><div className="contacts">{contacts.map((x,i)=><div key={x}><i>{x.slice(0,1)}</i><span><b>{x}</b><small>{i<2?'Client / Agency':'Creative contact'}</small></span></div>)}</div></Panel>}
function Network({notify}){return <><div className="network-filter"><b>Discover creatives</b><select><option>All roles</option>{roles.map(r=><option key={r}>{r}</option>)}</select><select><option>Paris</option><option>France</option><option>Europe</option></select></div><div className="network-grid">{['Marie Dupont','Leo Martin','Sofia Bernard','Thomas Leroy','Claire Moreau','Alex Renard'].map((n,i)=><article key={n}><div className={'avatar a'+i}>{n.slice(0,1)}</div><b>{n}</b><small>{roles[i+2]}</small><span>Paris · Available</span><button onClick={()=>notify('Invitation sent')}>Invite to project</button></article>)}</div></>}
function Messages({notify}){return <div className="messages"><div className="channels"><b>PROJECT CHANNELS</b>{['# General','# Creative','# Production','# Client'].map(x=><button key={x}>{x}</button>)}</div><Chat notify={notify}/></div>}
function Chat({notify}){const [msg,setMsg]=useState('');const [messages,setMessages]=useState([{n:'Anna',t:'The location is confirmed for tomorrow.'},{n:'Nicholas',t:'Perfect. I will update the shot list.'}]);return <div className="chat"><div className="chat-log">{messages.map((m,i)=><div key={i}><b>{m.n}</b><p>{m.t}</p></div>)}</div><div className="chat-input"><input placeholder="Write a message…" value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()}/><button onClick={send}>Send</button></div></div>;function send(){if(msg.trim()){setMessages([...messages,{n:'Nicholas',t:msg}]);setMsg('');notify('Message sent')}}}
function Casting(){return <><div className="casting-tabs"><b>All 24</b><span>Shortlist 8</span><span>Selected 4</span></div><div className="casting-grid">{['Alex','Jordan','Camille','Noah','Robin','Lou'].map((n,i)=><article key={n}><div className={'cast-photo cp'+i}/><b>{n}</b><small>Paris · Athlete / Model</small><div><button>☆ Shortlist</button><button>✓ Select</button></div></article>)}</div></>}
function Budget({project,setModal}){const rows=[['Photography',2500],['Talent',2800],['Styling',1200],['Equipment',850],['Location',1000],['Transport',500],['Catering',300]];return <div><div className="budget-total"><div><small>TOTAL BUDGET</small><b>€{project.budget.toLocaleString()}</b></div><div><small>SPENT</small><b>€{project.spent.toLocaleString()}</b></div><div><small>REMAINING</small><b>€{Math.max(project.budget-project.spent,0).toLocaleString()}</b></div></div><button className="primary inline" onClick={()=>setModal('expense')}>＋ Add Expense</button><div className="budget-table"><div><b>Category</b><b>Budget</b><b>Spent</b></div>{rows.map((r,i)=><div key={r[0]}><span>{r[0]}</span><span>€{r[1].toLocaleString()}</span><span>€{Math.round((project.spent*(i+1))/20).toLocaleString()}</span></div>)}</div></div>}
function Files({notify}){return <div className="files"><button className="upload" onClick={()=>notify('File upload interface ready for cloud connection')}>＋ Upload Files</button>{['Contracts','Moodboard Exports','Call Sheets','Client Files','Invoices'].map(x=><article key={x}>▱ <b>{x}</b><small>Open folder →</small></article>)}</div>}
function ProjectModal({onClose,onCreate}){const [form,setForm]=useState({name:'',client:'',location:'Paris, France',date:'',budget:''});return <div className="modal"><div><div className="modal-head"><h2>New Project</h2><button onClick={onClose}>×</button></div>{[['name','Project name'],['client','Client / brand'],['location','Location'],['date','Shoot date'],['budget','Budget (€)']].map(([k,p])=><input key={k} type={k==='budget'?'number':k==='date'?'date':'text'} placeholder={p} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>) }<button className="primary full" onClick={()=>form.name.trim()&&onCreate(form)}>Create Project</button></div></div>}
function SimpleModal({title,placeholder,action,onClose,onSubmit}){const [v,setV]=useState('');return <div className="modal"><div><div className="modal-head"><h2>{title}</h2><button onClick={onClose}>×</button></div><input autoFocus placeholder={placeholder} value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>e.key==='Enter'&&onSubmit(v)}/><button className="primary full" onClick={()=>onSubmit(v)}>{action}</button></div></div>}
function ExpenseModal({onClose,onSubmit}){const [name,setName]=useState('');const [amount,setAmount]=useState('');return <div className="modal"><div><div className="modal-head"><h2>Add Expense</h2><button onClick={onClose}>×</button></div><input placeholder="Expense description" value={name} onChange={e=>setName(e.target.value)}/><input type="number" placeholder="Amount (€)" value={amount} onChange={e=>setAmount(e.target.value)}/><button className="primary full" onClick={()=>onSubmit(name,amount)}>Add Expense</button></div></div>}
