'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '../lib/supabase-browser';
import Paywall from './paywall';

const modules=['Overview','Projects','Clients','Leads','Moodboards','Casting','Crew','Schedule','Tasks','Expenses','Estimates','Invoices','Files','Messages','Call Sheet','AI Assistant'];
const config={
 Clients:{table:'clients',title:'CLIENT CRM',fields:['name','email','phone'],cols:['NAME','EMAIL','PHONE']},
 Leads:{table:'clients',title:'LEADS',fields:['name','email','phone'],cols:['NAME','EMAIL','PHONE']},
 Tasks:{table:'tasks',title:'TASKS',fields:['title','status','due_date'],cols:['TASK','STATUS','DUE']},
 Casting:{table:'casting_candidates',title:'CASTING',fields:['name','role','status'],cols:['TALENT','ROLE','STATUS']},
 Crew:{table:'crew_profiles',title:'CREW',fields:['first_name','role','city'],cols:['NAME','ROLE','CITY']},
 Schedule:{table:'project_events',title:'SCHEDULE',fields:['title','start_at','location'],cols:['EVENT','TIME','LOCATION']},
 Expenses:{table:'expenses',title:'EXPENSES',fields:['description','amount','category'],cols:['ITEM','AMOUNT','CATEGORY']},
 Estimates:{table:'estimates',title:'ESTIMATES',fields:['number','status','total'],cols:['NUMBER','STATUS','TOTAL']},
 Moodboards:{table:'moodboards',title:'MOODBOARDS',fields:['title','status','created_at'],cols:['TITLE','STATUS','CREATED']},
 Files:{table:'project_files',title:'FILES',fields:['name','file_type','created_at'],cols:['FILE','TYPE','CREATED']},
 Messages:{table:'project_messages',title:'MESSAGES',fields:['body','created_at','sender_id'],cols:['MESSAGE','DATE','FROM']},
 Invoices:{table:'invoices',title:'INVOICES',fields:['invoice_number','status','total'],cols:['NUMBER','STATUS','TOTAL'],api:true}
};
const fallback=[{name:'Paris Fashion Campaign',type:'CAMPAIGN',date:'02 OCT 2026',status:'PRE-PRODUCTION',progress:72},{name:'Normandy Editorial',type:'EDITORIAL',date:'15 OCT 2026',status:'PLANNING',progress:38},{name:'Beauty Test — Paris',type:'MODEL TEST',date:'21 OCT 2026',status:'CONFIRMED',progress:54}];

export default function Page(){
 const [active,setActive]=useState('Overview'),[menuOpen,setMenuOpen]=useState(false),[projects,setProjects]=useState([]),[rows,setRows]=useState([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[user,setUser]=useState(null),[projectId,setProjectId]=useState(''),[editing,setEditing]=useState(null),[creating,setCreating]=useState(false),[stats,setStats]=useState({tasks:0,budget:0,shoots:0}),[projectForm,setProjectForm]=useState(null),[projectEdit,setProjectEdit]=useState(null),[access,setAccess]=useState('checking');
 useEffect(()=>{const saved=localStorage.getItem('set_active');if(saved&&modules.includes(saved))setActive(saved)},[]);useEffect(()=>{localStorage.setItem('set_active',active)},[active]);
 useEffect(()=>{let live=true;(async()=>{try{const s=createClient(),{data:{user:u}}=await s.auth.getUser();if(!live)return;setUser(u||null);if(!u){setProjects(fallback);setNotice('Sign in to sync your production workspace.');return}const {data,error}=await s.from('projects').select('*').eq('owner_id',u.id).order('created_at',{ascending:false});if(error)throw error;setProjects((data||[]).map(normalizeProject));if(data?.[0]){const saved=typeof window!=='undefined'?localStorage.getItem('set_project'):'';setProjectId(data.some(x=>x.id===saved)?saved:data[0].id)}}catch(e){setProjects(fallback);setNotice('Workspace is available in preview mode.')}finally{if(live)setLoading(false)}})();return()=>{live=false}},[]);
 useEffect(()=>{if(!user||!config[active]){setRows([]);return}let live=true;(async()=>{try{const s=createClient(),c=config[active];let q=s.from(c.table).select('*');if(['Clients','Leads','Crew','Tasks','Expenses','Estimates'].includes(active))q=q.eq('owner_id',user.id);if(projectId&&!['Clients','Leads','Crew','Invoices'].includes(active))q=q.eq('project_id',projectId);if(active==='Leads')q=q.eq('status','lead');if(active==='Clients')q=q.eq('status','client');if(c.api){const res=await fetch('/api/invoices');const json=await res.json();if(!res.ok)throw new Error(json.error||'Could not load invoices');if(live){setRows(json.invoices||[]);setNotice('')}return}const {data,error}=await q.limit(100);if(error)throw error;if(live){setRows(data||[]);setNotice('')}}catch(e){if(live){setRows([]);setNotice(active+' is ready, but its database view is not available yet.')}}})();return()=>{live=false}},[active,user,projectId]);
 useEffect(()=>{if(!user)return;(async()=>{try{const s=createClient();const [t,e,v]=await Promise.all([s.from('tasks').select('id',{count:'exact',head:true}).eq('owner_id',user.id),s.from('expenses').select('amount').eq('owner_id',user.id),s.from('project_events').select('id',{count:'exact',head:true}).in('project_id',projects.filter(p=>p.id).map(p=>p.id))]);setStats({tasks:t.count||0,budget:(e.data||[]).reduce((a,x)=>a+Number(x.amount||0),0),shoots:v.count||0})}catch{}})()},[user,rows]);
 useEffect(()=>{if(projectId&&typeof window!=='undefined')localStorage.setItem('set_project',projectId)},[projectId]);useEffect(()=>{if(!user){setAccess('checking');return}(async()=>{try{const r=await fetch('/api/billing/status',{cache:'no-store'});const j=await r.json();setAccess(r.ok&&j.hasAccess?'granted':'blocked')}catch{setAccess('blocked')}})()},[user]);
 const visible=useMemo(()=>projects.filter(p=>(p.name||'').toLowerCase().includes(query.toLowerCase())),[projects,query]);const currentProject=projects.find(p=>p.id===projectId);
 async function addProject(){if(!user){location.href='/login?next=/';return}setProjectForm({name:'',status:'lead'})}
 async function addRecord(){if(!user||!config[active])return;if(active==='Files'){document.getElementById('set-file-input')?.click();return;}if(!projectId&&!['Clients','Leads','Crew','Invoices'].includes(active)){setNotice('Create or select a project first.');return}setCreating(true)}
 async function uploadFile(file){if(!file||!projectId)return;try{setNotice('UPLOADING FILE…');const s=createClient();const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${projectId}/${Date.now()}-${safe}`;const up=await s.storage.from('set-project-files').upload(path,file,{upsert:false});if(up.error)throw up.error;const {data,error}=await s.from('project_files').insert({project_id:projectId,name:file.name,file_type:file.type||'file',folder:'General',storage_path:path,mime_type:file.type||null,size_bytes:file.size,uploaded_by:user.id}).select().single();if(error)throw error;setRows(v=>[data,...v]);setNotice('FILE UPLOADED')}catch(e){setNotice('Could not upload file: '+e.message)}}
 async function createRecord(values){
  try{
   if(active==='Messages'&&!String(values.body||'').trim())throw new Error('Message cannot be empty');if(active==='Expenses'&&Number(values.amount||0)<0)throw new Error('Amount cannot be negative');if(active==='Invoices'){const amount=Number(values.total||0);if(!values.client_name||amount<=0)throw new Error('Client name and a positive amount are required');const res=await fetch('/api/invoices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_name:values.client_name,client_email:values.client_email||'',currency:'EUR',items:[{description:values.description||'Photography services',quantity:1,unit_price:amount,vat_rate:0}]})});const json=await res.json();if(!res.ok)throw new Error(json.error||'Could not create invoice');setRows(v=>[json.invoice,...v]);setCreating(false);return}
   const cfg=config[active],base={...values};if(['Clients','Leads','Crew','Tasks','Expenses','Estimates'].includes(active))base.owner_id=user.id;if(active==='Messages')base.sender_id=user.id;if(active==='Expenses'&&base.amount!=='')base.amount=Number(base.amount);if(projectId&&!['Clients','Leads','Crew','Invoices'].includes(active))base.project_id=projectId;if(active==='Leads')base.status='lead';if(active==='Tasks'&&!base.status)base.status='todo';if(active==='Casting'&&!base.status)base.status='maybe';if(active==='Moodboards'&&!base.status)base.status='draft';
   const s=createClient(),{data,error}=await s.from(cfg.table).insert(base).select().single();if(error)throw error;setRows(v=>[data,...v]);setCreating(false);setNotice('')
  }catch(e){setNotice('Could not create record: '+e.message)}
 }
 async function castingAction(){const email=prompt('Recipient email');if(!email||!projectId)return;const items=rows.filter(x=>String(x.status||'').toLowerCase()==='selected').map(x=>({name:x.name,talentName:x.name,role:x.role,status:x.status,city:x.city,height:x.height,bust:x.bust,waist:x.waist,hips:x.hips,shoes:x.shoes,availability:x.availability,email:x.email,phone:x.phone,notes:x.notes,src:x.image_url||x.photo_url||x.src}));if(!items.length){setNotice('Select casting candidates first.');return}try{const res=await fetch('/api/casting/pdf-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,email,items})});const json=await res.json();if(!res.ok)throw new Error(json.error||'Could not send casting PDF');setNotice('Casting selection sent.')}catch(e){setNotice(e.message)}}
 async function invoiceAction(kind,row){try{if(kind==='pdf'){window.open('/api/invoices/'+row.id+'/pdf','_blank');return}if(kind==='send'){if(!confirm('Send invoice to '+(row.client_email||'client')+'?'))return;const res=await fetch('/api/invoices/'+row.id+'/send',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const json=await res.json();if(!res.ok)throw new Error(json.error||'Could not send invoice');setRows(v=>v.map(x=>x.id===row.id?{...x,status:'sent'}:x));}}catch(e){setNotice(e.message)}}
 async function saveEdit(values){try{const s=createClient();let q=s.from(config[active].table).update(values).eq('id',editing.id);if(['Clients','Leads','Crew','Tasks','Expenses','Estimates'].includes(active))q=q.eq('owner_id',user.id);const {data,error}=await q.select().single();if(error)throw error;setRows(v=>v.map(x=>x.id===data.id?data:x));setEditing(null);setNotice('')}catch(e){setNotice('Could not update record: '+e.message)}}
 async function removeRecord(row){if(!confirm('Delete this record?'))return;try{if(active==='Invoices'){setNotice('Invoices are financial records and cannot be deleted from the workspace.');return}const s=createClient();let q=s.from(config[active].table).delete().eq('id',row.id);if(['Clients','Leads','Crew','Tasks','Expenses','Estimates'].includes(active))q=q.eq('owner_id',user.id);const {error}=await q;if(error)throw error;setRows(v=>v.filter(x=>x.id!==row.id))}catch(e){setNotice('Could not delete record: '+e.message)}}
 async function refreshAccess(){setAccess('checking');try{const r=await fetch('/api/billing/status',{cache:'no-store'});const j=await r.json();setAccess(r.ok&&j.hasAccess?'granted':'blocked')}catch{setAccess('blocked')}}
 async function signOut(){const s=createClient();await s.auth.signOut();localStorage.removeItem('set_project');localStorage.removeItem('set_active');location.href='/login'}
 if(user&&access==='blocked')return <Paywall onRetry={refreshAccess}/>;if(user&&access==='checking')return <main className="accessLoading"><div className="brand">SET</div><span>CHECKING MEMBERSHIP…</span></main>;
 return <main className="shell"><header><div className="brand">SET</div><button className="menuToggle" aria-label="Open navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?"CLOSE":"MENU"}</button><div className="headerRight"><span>CREATIVE PRODUCTION OS</span>{user?<button className="accountBtn" onClick={signOut}>LOG OUT</button>:<button className="accountBtn" onClick={()=>location.href='/login'}>LOG IN</button>}</div></header><div className="layout"><aside className={menuOpen?"menuOpen":""}><nav>{modules.map(m=><button key={m} onClick={()=>{setActive(m);setNotice('');setMenuOpen(false)}} className={active===m?'active':''}>{m.toUpperCase()}</button>)}</nav><div className="asideFoot">EFIMTSEV / PARIS<br/>V2.4</div></aside><section className="content"><div className="eyebrow">WORKSPACE / {active.toUpperCase()}{currentProject&&active!=='Overview'&&active!=='Projects'?` / ${currentProject.name.toUpperCase()}`:''}</div><div className="hero"><h1>{active}</h1><div className="heroActions">{projects.length>0&&<select className="projectSelect" value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.filter(p=>p.id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}{active==='Files'&&<input id="set-file-input" type="file" hidden onChange={e=>{uploadFile(e.target.files?.[0]);e.target.value=''}}/>}<button className="primary" onClick={config[active]?addRecord:addProject}>{config[active]?'+ NEW RECORD':'+ NEW PROJECT'}</button></div></div>{notice&&<p className="auth-status">{notice}</p>}{active==='Overview'||active==='Projects'?<Projects projects={visible} loading={loading} query={query} setQuery={setQuery} stats={stats} editProject={setProjectEdit}/>:config[active]?<DataModule name={active} rows={rows} removeRecord={removeRecord} editRecord={setEditing} invoiceAction={invoiceAction} castingAction={castingAction}/>:<Special name={active} projectId={projectId} user={user}/>}{projectEdit&&<ProjectEditor row={projectEdit} close={()=>setProjectEdit(null)} saved={x=>{setProjects(v=>v.map(p=>p.id===x.id?normalizeProject(x):p));setProjectEdit(null)}} user={user}/>} {projectForm&&<CreateProject row={projectForm} close={()=>setProjectForm(null)} created={p=>{setProjects(v=>[normalizeProject(p),...v]);setProjectId(p.id);setProjectForm(null)}} user={user}/>} {editing&&<Editor name={active} row={editing} close={()=>setEditing(null)} save={saveEdit}/>} {creating&&<CreateForm name={active} close={()=>setCreating(false)} save={createRecord}/>}</section></div></main>
}
function Projects({projects,loading,query,setQuery,stats,editProject}){const activeProjects=projects.filter(p=>p.status!=='CANCELLED');return <><div className="metrics"><article><b>{loading?'—':projects.filter(p=>p.status!=='CANCELLED').length}</b><span>ACTIVE PROJECTS</span></article><article><b>{stats.tasks}</b><span>TASKS</span></article><article><b>€{Math.round(stats.budget).toLocaleString()}</b><span>EXPENSES</span></article><article><b>{stats.shoots}</b><span>SCHEDULED EVENTS</span></article></div><div className="toolbar"><h2>PROJECTS</h2><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="SEARCH PROJECTS"/></div><div className="table"><div className="row head"><span>PROJECT</span><span>TYPE</span><span>DATE</span><span>STATUS</span><span>PROGRESS</span></div>{activeProjects.map((p,i)=><div className="row" key={p.id||i}><strong>{p.name}</strong><span>{p.type}</span><span>{fmt(p.date)}</span><span>{p.status}</span><span>{p.progress}%</span><button className="projectEdit" onClick={()=>editProject(p)}>EDIT</button></div>)}</div></>}
function DataModule({name,rows,removeRecord,editRecord,invoiceAction,castingAction}){const c=config[name],total=name==='Expenses'?rows.reduce((a,x)=>a+Number(x.amount||0),0):null;return <div className="data-module"><div className="toolbar"><h2>{c.title}</h2><div className="moduleTools">{name==='Casting'&&<button className="outline small" onClick={castingAction}>EMAIL SELECTED CASTING PDF</button>}<span className="count">{rows.length} RECORDS{total!==null?' · €'+total.toLocaleString():''}</span></div></div><div className="data-table"><div className="data-row head">{c.cols.map(x=><span key={x}>{x}</span>)}</div>{rows.length?rows.map((r,i)=><div className="data-row" key={r.id||i}>{c.fields.map((f,j)=><span key={f} className={j===0?'lead':''}>{fmt(r[f])}</span>)}<div className="rowActions">{name==='Invoices'?<><button onClick={()=>invoiceAction('pdf',r)}>PDF</button><button onClick={()=>invoiceAction('send',r)}>SEND</button></>:<button onClick={()=>editRecord(r)}>EDIT</button>}{name!=='Invoices'&&<button onClick={()=>removeRecord(r)}>×</button>}</div></div>):<div className="empty">NO RECORDS YET</div>}</div></div>}
function ProjectEditor({row,close,saved,user}){const [name,setName]=useState(row.name),[status,setStatus]=useState(String(row.status||'lead').toLowerCase().replaceAll(' ','_')),[address,setAddress]=useState(row.address||''),[locationNotes,setLocationNotes]=useState(row.location_notes||''),[parking,setParking]=useState(row.parking_info||''),[transit,setTransit]=useState(row.transit_info||''),[directions,setDirections]=useState(row.directions_url||''),[saving,setSaving]=useState(false);async function submit(){if(!name.trim()||saving)return;setSaving(true);const s=createClient();const r=await s.from('projects').update({name:name.trim(),status,address,location_notes:locationNotes,parking_info:parking,transit_info:transit,directions_url:directions}).eq('id',row.id).eq('owner_id',user.id).select().single();if(!r.error)saved(r.data);else setSaving(false)}return <div className="modalBack"><div className="editor"><div className="editorHead"><span>EDIT PROJECT</span><button onClick={close}>×</button></div><label>PROJECT NAME<input value={name} onChange={e=>setName(e.target.value)}/></label><label>STATUS<select value={status} onChange={e=>setStatus(e.target.value)}><option value="lead">LEAD</option><option value="proposal">PROPOSAL</option><option value="pre_production">PRE-PRODUCTION</option><option value="confirmed">CONFIRMED</option><option value="shooting">SHOOTING</option><option value="post_production">POST-PRODUCTION</option><option value="delivered">DELIVERED</option><option value="completed">COMPLETED</option><option value="cancelled">CANCELLED</option></select></label><label>ADDRESS<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label>LOCATION NOTES<input value={locationNotes} onChange={e=>setLocationNotes(e.target.value)}/></label><label>PARKING<input value={parking} onChange={e=>setParking(e.target.value)}/></label><label>TRANSIT<input value={transit} onChange={e=>setTransit(e.target.value)}/></label><label>DIRECTIONS URL<input value={directions} onChange={e=>setDirections(e.target.value)}/></label><button className="primary" disabled={saving} onClick={submit}>{saving?'SAVING…':'SAVE PROJECT'}</button></div></div>}
function CreateProject({row,close,created,user}){const [name,setName]=useState(row.name),[saving,setSaving]=useState(false);async function submit(){if(!name.trim()||saving)return;setSaving(true);const s=createClient(),{data,error}=await s.from('projects').insert({name:name.trim(),status:'lead',owner_id:user.id}).select().single();if(error){setSaving(false);return}created(data)}return <div className="modalBack"><div className="editor"><div className="editorHead"><span>NEW PROJECT</span><button onClick={close}>×</button></div><label>PROJECT NAME<input value={name} onChange={e=>setName(e.target.value)} autoFocus/></label><button className="primary" disabled={saving} onClick={submit}>{saving?'CREATING…':'CREATE PROJECT'}</button></div></div>}
function CreateForm({name,close,save}){const cfg=config[name],fields=name==='Invoices'?['client_name','client_email','description','total']:name==='Estimates'?['total']:name==='Messages'?['body']:name==='Files'?['name','file_type']:cfg.fields.filter(f=>!['created_at','invoice_number','estimate_number'].includes(f)),[form,setForm]=useState(()=>Object.fromEntries(fields.map(f=>[f,f==='status'?'draft':'']))),[saving,setSaving]=useState(false);async function submit(){if(saving)return;setSaving(true);await save(form);setSaving(false)}return <div className="modalBack"><div className="editor"><div className="editorHead"><span>NEW {name.toUpperCase()}</span><button onClick={close}>×</button></div>{fields.map(f=><label key={f}>{f.replaceAll('_',' ').toUpperCase()}<input type={f.includes('email')?'email':f.includes('date')||f==='start_at'?'datetime-local':f==='amount'||f==='total'?'number':'text'} value={form[f]} min={f==='amount'||f==='total'?0:undefined} onChange={e=>setForm(v=>({...v,[f]:e.target.value}))}/></label>)}<button className="primary" disabled={saving} onClick={submit}>{saving?'CREATING…':'CREATE'}</button></div></div>}
function Editor({name,row,close,save}){const c=config[name],[form,setForm]=useState(()=>Object.fromEntries(c.fields.filter(f=>f!=='created_at').map(f=>[f,row[f]??''])));return <div className="modalBack"><div className="editor"><div className="editorHead"><span>EDIT {name.toUpperCase()}</span><button onClick={close}>×</button></div>{Object.keys(form).map(f=><label key={f}>{f.replaceAll('_',' ').toUpperCase()}<input value={form[f]} onChange={e=>setForm(v=>({...v,[f]:e.target.value}))}/></label>)}<button className="primary" onClick={()=>save(form)}>SAVE CHANGES</button></div></div>}
function Special({name,projectId,user}){const [brief,setBrief]=useState(''),[result,setResult]=useState(''),[aiBusy,setAiBusy]=useState(false),[call,setCall]=useState({project:null,events:[],crew:[],cast:[]});
 useEffect(()=>{if(name!=='Call Sheet'||!user||!projectId)return;(async()=>{try{const s=createClient();const [{data:project},{data:events},{data:crew},{data:cast}]=await Promise.all([s.from('projects').select('*').eq('id',projectId).eq('owner_id',user.id).maybeSingle(),s.from('project_events').select('*').eq('project_id',projectId).order('start_at'),s.from('project_crew').select('*,crew_profiles(*)').eq('project_id',projectId),s.from('casting_candidates').select('*').eq('project_id',projectId)]);setCall({project,events:events||[],crew:crew||[],cast:cast||[]})}catch{}})()},[name,projectId,user]);
 async function generateProjectPlan(){if(!brief.trim()||!projectId||aiBusy)return;setAiBusy(true);try{const s=createClient();let {data:b,error}=await s.from('project_briefs').select('*').eq('project_id',projectId).eq('owner_id',user.id).maybeSingle();if(error)throw error;if(b){const u=await s.from('project_briefs').update({brief:brief.trim()}).eq('id',b.id).select().single();if(u.error)throw u.error;b=u.data}else{const i=await s.from('project_briefs').insert({project_id:projectId,owner_id:user.id,brief:brief.trim()}).select().single();if(i.error)throw i.error;b=i.data}const planText=buildPlan(brief);const plan={text:planText,generated_at:new Date().toISOString()};const saved=await s.from('ai_project_plans').insert({project_id:projectId,brief_id:b.id,owner_id:user.id,plan}).select().single();if(saved.error)throw saved.error;await s.from('project_ai_memory').insert({project_id:projectId,memory_type:'production_brief',content:{brief:brief.trim(),plan_id:saved.data.id},source:'set_workspace'});setResult(planText)}catch(e){setResult('Could not save production plan: '+e.message)}finally{setAiBusy(false)}}
 if(name==='AI Assistant')return <div className="special"><p className="auth-status">Production planner — saves the brief, plan and project memory in this workspace.</p><div className="eyebrow">SET / AI PRODUCTION ASSISTANT</div><h2>Turn a brief into a production plan.</h2><textarea value={brief} onChange={e=>setBrief(e.target.value)} placeholder="Paste the shoot brief, dates, location, deliverables and constraints…"/><button className="primary" disabled={aiBusy||!projectId} onClick={generateProjectPlan}>{aiBusy?'GENERATING…':'GENERATE + SAVE PLAN'}</button>{result&&<pre className="plan">{result}</pre>}</div>;if(name==='Call Sheet')return <div className="special callSheet"><div className="eyebrow">SET / CALL SHEET</div><h2>{call.project?.name||'Production call sheet'}</h2><div className="callGrid"><section><b>SCHEDULE</b>{call.events.length?call.events.map(x=><p key={x.id}>{fmt(x.start_at)} · {x.title||'Event'}{x.location?' · '+x.location:''}</p>):<p>No schedule entries.</p>}</section><section><b>CREW</b>{call.crew.length?call.crew.map(x=><p key={x.id}>{[x.crew_profiles?.first_name,x.crew_profiles?.last_name].filter(Boolean).join(' ')||'Crew'} · {x.crew_profiles?.role||x.role||'Team'}</p>):<p>No crew assigned.</p>}</section><section><b>CAST</b>{call.cast.length?call.cast.map(x=><p key={x.id}>{x.name||'Talent'}{x.role?' · '+x.role:''}</p>):<p>No cast assigned.</p>}</section><section><b>LOCATION</b><p>{call.project?.address||call.project?.location||'Add project location.'}</p>{call.project?.location_notes&&<p>{call.project.location_notes}</p>}{call.project?.parking_info&&<p><b>PARKING</b><br/>{call.project.parking_info}</p>}{call.project?.transit_info&&<p><b>TRANSIT</b><br/>{call.project.transit_info}</p>}{call.project?.directions_url&&<p><a href={call.project.directions_url} target="_blank" rel="noreferrer">OPEN DIRECTIONS ↗</a></p>}</section></div><button className="outline" onClick={()=>window.print()}>PRINT / SAVE PDF</button></div>;return <div className="module"><h2>Project workspace.</h2></div>}
function buildPlan(b){if(!b.trim())return'Add a project brief first.';return ['PRE-PRODUCTION','• Confirm brief, usage, deliverables and budget','• Lock location, permits and insurance','• Confirm casting and crew','• Build moodboard and shot list','','SHOOT DAY','• Call sheet + contacts','• Equipment / lighting check','• Capture backup workflow','','POST-PRODUCTION','• Selection and client approval','• Retouch / colour / exports','• Delivery, invoice and archive','','BRIEF NOTES',b.trim()].join('\n')}
function normalizeProject(p){return{...p,id:p.id,name:p.name||p.title||'Untitled project',type:String(p.project_type||p.type||'PROJECT').toUpperCase(),date:p.date||p.shoot_date||p.start_date||'TBD',status:String(p.status||'LEAD').replaceAll('_',' ').toUpperCase(),progress:Number(p.progress||0)}}
function fmt(v){if(v===null||v===undefined||v==='')return'—';if(typeof v==='number')return String(v);const s=String(v);if(/^\d{4}-\d{2}-\d{2}T/.test(s)){const d=new Date(s);if(!Number.isNaN(d.valueOf()))return d.toLocaleString(undefined,{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}return s.length>80?s.slice(0,77)+'…':s}
